# File: .github/workflows/ci.yml
# Plan (pseudocode)
# 1) Trigger on push/PR to main|master.
# 2) Setup Python 3.12, cache pip, install project + CI tools.
# 3) Run pre-commit on all files (ruff/black/nbqa/nbstripout hooks).
# 4) Run pytest with coverage; expose coverage.xml as artifact.
# 5) Provide MLflow local file backend so any tracking calls succeed.
# 6) Use concurrency to cancel stale runs.

name: ci

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install project & CI tools
        run: |
          python -m pip install --upgrade pip
          # Install your package (editable if pyproject present)
          if [ -f pyproject.toml ]; then pip install -e .; fi
          # Ensure tools used in hooks/tests exist in the runner
          pip install \
            pre-commit \
            pytest pytest-cov \
            mlflow pandas scikit-learn fastapi uvicorn joblib python-dotenv rich nbqa nbstripout

      - name: Pre-commit (ruff/black/nbqa/etc.)
        run: |
          pre-commit run --all-files --show-diff-on-failure

      - name: Run tests
        env:
          MLFLOW_TRACKING_URI: file:./mlruns
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=src --cov-report=xml

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          if-no-files-found: ignore
