# file: docker-compose.yml
version: "3.8"

x-common: &common
  image: cadd-data:latest
  build:
    context: .
    dockerfile: Dockerfile
  working_dir: /app
  volumes:
    - ./config:/app/config
    - ./data:/app/data
    - ./models:/app/models
    - ./reports:/app/reports

services:
  train:
    <<: *common
    command: >
      bash -lc "addiction-train --config config/config.yaml"

  evaluate:
    <<: *common
    command: >
      bash -lc "addiction-evaluate --config config/config.yaml --mode splits"

  predict:
    <<: *common
    environment:
      INPUT: ${INPUT:-data/raw/raw.csv}
    command: >
      bash -lc "addiction-predict --config config/config.yaml --input ${INPUT}"

  ingest:
    <<: *common
    command: >
      bash -lc "addiction-ingest --config config/config.yaml --schema config/schema.yaml"

  watch:
    <<: *common
    command: >
      bash -lc "addiction-watch --config config/config.yaml --schema config/schema.yaml"
    restart: unless-stopped

  test:
    <<: *common
    command: >
      bash -lc "pytest -q"
