# file: docker-compose.yml  (self-contained + persistent artifacts)
version: "3.9"

volumes:
  data: {}
  reports: {}
  models: {}

services:
  watcher:
    build: .
    image: cigarette-and-drinking-data:latest
    working_dir: /app
    restart: unless-stopped
    command:
      - addiction-watch
      - --config
      - config/config.yaml
      - --schema
      - config/schema.yaml
      - --outliers
      - iqr
      - --iqr-k
      - "1.5"
    volumes:
      - data:/app/data
      - reports:/app/reports
      - models:/app/models
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'addiction-watch' >/dev/null || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 3

