# File: configs/default.yaml
# Minimal, pragmatic project config used by CLI scripts (clean/sample) and data ops.
# Only the keys you need must be read by your scripts; extra keys are harmless.

paths:
  raw_dir: data/raw
  sample_dir: data/sample
  interim_dir: data/interim
  processed_dir: data/processed
  reports_dir: reports

io:
  read_kwargs:
    low_memory: false
    encoding: utf-8
    dtype_backend: numpy_nullable   # pandas 2.x nullable dtypes
    na_values: ["", "NA", "N/A", "null", "None"]
  write_kwargs:
    index: false
    encoding: utf-8
    # compression: null  # e.g., {method: gzip}

cleaning:
  # Column selection/shape
  keep_columns: []          # if non-empty, select these columns first
  drop_columns: []          # columns to drop if present
  rename: {}                # mapping: {old: new}
  colname_style: snakecase  # one of: none|lower|snakecase

  # Row-level
  drop_duplicates: true
  drop_rows_all_na: true
  min_non_na_ratio: 0.0     # drop rows below this non-NA ratio (0.0 disables)

  # Value normalization
  trim_whitespace: true
  normalize_unicode: true
  strip_punctuation_columns: false

  # Type casting & parsing (applied after rename)
  dtypes: {}                # {column: dtype}
  parse_dates: []           # list of date columns
  bool_mapping: {"yes": true, "no": false, "y": true, "n": false}

  # Missing values handling (generic fallbacks)
  impute:
    numeric: median         # mean|median|zero|none
    categorical: most_frequent  # most_frequent|constant|none
    constants: {}           # {column: value} overrides

  # Outliers (optional; your cleaner may ignore if unimplemented)
  outliers:
    method: none            # none|zscore|iqr
    zscore_threshold: 4.0
    iqr_k: 1.5
    columns: []

export:
  stem: auto                # matches `--stem auto` in Makefile
  suffix: cleaned           # filename suffix when writing outputs
  subdir: processed         # write under this subdir by default

sample:
  n_default: 100
  random_state: 1337

# References to other configs (optional convenience)
references:
  params: configs/params.yaml
  schema: configs/schema.yaml
  logging: configs/logging.yaml
