project_name: addiction_ds
random_state: 42

paths:
  data_dir: data
  raw: data/raw/addiction_population_data.csv
  sample_input: data/sample/sample_100_rows.csv
  reports_dir: reports
  schema: configs/schema.yaml
