# File: configs/schema.yaml
columns:
  id:                 {type: integer, required: true,  min: 1}
  name:               {type: string,  required: true,  max_len: 100}
  age:                {type: integer, required: true,  min: 0,  max: 120}
  gender:             {type: category, required: true,  allowed: [Female, Male, Other]}
  country:            {type: string,  required: true}
  city:               {type: string,  required: true}

  education_level:    {type: category, allowed: [Primary, Secondary, High School, College, University, Postgraduate, None]}
  employment_status:  {type: category, allowed: [Employed, Retired, Self-Employed, Student, Unemployed]}
  annual_income_usd:  {type: integer, min: 0,  max: 1000000}
  marital_status:     {type: category, allowed: [Single, Married, Divorced, Widowed, "In a relationship"]}
  children_count:     {type: integer, min: 0,  max: 10}

  smokes_per_day:           {type: integer, min: 0,  max: 100}
  drinks_per_week:          {type: integer, min: 0,  max: 100}
  age_started_smoking:      {type: integer, min: 5,  max: 100}
  age_started_drinking:     {type: integer, min: 5,  max: 100}
  attempts_to_quit_smoking: {type: integer, min: 0,  max: 100}
  attempts_to_quit_drinking:{type: integer, min: 0,  max: 100}

  has_health_issues:   {type: boolean}
  mental_health_status:{type: category, allowed: [Good, Average, Poor]}
  exercise_frequency:  {type: category, allowed: [Daily, Weekly, Rarely, Never]}
  diet_quality:        {type: category, allowed: [Good, Average, Poor]}
  sleep_hours:         {type: number,  min: 0,  max: 24}
  bmi:                 {type: number,  min: 5,  max: 80}
  social_support:      {type: category, allowed: [Strong, Moderate, Weak, None]}
  therapy_history:     {type: category, allowed: [None, Past, Current]}

primary_key: [id]
min_rows: 1
