# File: configs/schema.yaml
# Minimal, safe schema for addiction_population_data.csv
# Focuses on types + categories; tighten later if needed.

columns:
  id:
    type: integer
  name:
    type: string
  age:
    type: integer
  gender:
    type: string
    allowed: [Female, Male, Other]
  country:
    type: string
  city:
    type: string

  education_level:
    type: string
    allowed: [Primary, Secondary, "High School", College, University, Postgraduate, "None"]
  employment_status:
    type: string
    allowed: [Employed, Self-Employed, Unemployed, Student, Retired]
  annual_income_usd:
    type: integer
  marital_status:
    type: string
    allowed: [Single, Married, Divorced, Widowed, "In a relationship"]
  children_count:
    type: integer

  smokes_per_day:
    type: integer
  drinks_per_week:
    type: integer
  age_started_smoking:
    type: integer
  age_started_drinking:
    type: integer
  attempts_to_quit_smoking:
    type: integer
  attempts_to_quit_drinking:
    type: integer

  has_health_issues:
    type: boolean
  mental_health_status:
    type: string
    allowed: [Good, Average, Poor]
  exercise_frequency:
    type: string
    allowed: [Daily, Weekly, Rarely, Never]
  diet_quality:
    type: string
    allowed: [Good, Average, Poor]
  sleep_hours:
    type: number
  bmi:
    type: number
  social_support:
    type: string
    allowed: [Strong, Moderate, Weak, None]
  therapy_history:
    type: string
    allowed: [None, Past, Current]

primary_key:
  columns: [id]
  optional: true

min_rows: 1
